import React, { useEffect, useRef, useState } from 'react';
export default function MicrophoneCheck({ stream, onBusy }: { stream: MediaStream; onBusy: (busy: boolean) => void }) {
  const [level,setLevel]=useState(0), [recording,setRecording]=useState(false), [sample,setSample]=useState(''), [error,setError]=useState('');
  const recorder=useRef<MediaRecorder|null>(null), timer=useRef<ReturnType<typeof setTimeout>|null>(null), alive=useRef(true);
  useEffect(()=>{ alive.current=true; return()=>{alive.current=false; if(timer.current)clearTimeout(timer.current); if(recorder.current?.state==='recording')recorder.current.stop();}; },[]);
  useEffect(()=>()=>{if(sample)URL.revokeObjectURL(sample);},[sample]);
  useEffect(()=>{let context:AudioContext|undefined,frame=0;try{context=new AudioContext(); const analyser=context.createAnalyser();analyser.fftSize=256;context.createMediaStreamSource(stream).connect(analyser);const values=new Uint8Array(analyser.fftSize);const tick=()=>{analyser.getByteTimeDomainData(values);setLevel(Math.min(100,Math.sqrt(values.reduce((sum,v)=>sum+(v-128)**2,0)/values.length)*5));frame=requestAnimationFrame(tick);};tick();void context.resume().catch(()=>{});}catch{setError('The input meter is unavailable. You can still record a sample.');}return()=>{cancelAnimationFrame(frame);void context?.close().catch(()=>{});};},[stream]);
  const start=()=>{try{setError('');setSample('');const audio=new MediaStream(stream.getAudioTracks());const r=new MediaRecorder(audio),chunks:BlobPart[]=[];r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};r.onstop=()=>{if(timer.current)clearTimeout(timer.current);if(!alive.current)return;setRecording(false);onBusy(false);setSample(URL.createObjectURL(new Blob(chunks,{type:r.mimeType})));};r.onerror=()=>{if(alive.current){setError('Sample recording failed. Please try again.');setRecording(false);onBusy(false);}};recorder.current=r;r.start();setRecording(true);onBusy(true);timer.current=setTimeout(()=>{if(r.state==='recording')r.stop();},10000);}catch{setError('Sample recording is unavailable in this browser.');onBusy(false);}};
  return <section aria-label="Microphone check" className="w-full rounded-xl border border-[var(--stint-border)] p-4 space-y-3"><h2 className="text-sm font-semibold">Check your microphone</h2><p className="text-xs text-[var(--stint-text-muted)]">Speak naturally. Record up to 10 seconds and play it back to check volume and background noise. This sample stays in this browser and is not analysed.</p><meter className="w-full" aria-label="Microphone input level" min={0} max={100} value={level} /><button className="text-sm font-semibold text-[var(--stint-primary)]" onClick={recording?()=>recorder.current?.stop():start}>{recording?'Stop sample':'Record test sample'}</button>{sample&&<audio className="w-full" aria-label="Microphone test playback" controls src={sample} />}{error&&<p role="alert" className="text-sm">{error}</p>}</section>;
}
