import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiGet, apiPost } from '../lib/api';
import type { InterviewEntry } from '../constants';
import { passageState } from './ReadingPracticePlan';
type Assignment={id:number;content_id:number|null;question:string;note:string;status:string;available:boolean;created_at:string;completed_attempt_id:number|null;assigned_by_name:string};
type Payload={assignments:Assignment[];total:number;pageSize:number;passages?:{id:number;question:string;category:string}[];candidate?:{domain_name:string|null}};
const field='block w-full min-w-0 rounded-xl border border-[var(--stint-border)] bg-[var(--stint-bg)] p-2.5 text-sm';
export default function PracticeAssignments({staffCandidateId,passages=[],initialContentId,compact=false}:{staffCandidateId?:number;passages?:InterviewEntry[];initialContentId?:number|null;compact?:boolean}) {
 const [data,setData]=useState<Payload|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [actionError,setActionError]=useState(''),[failedAction,setFailedAction]=useState<{path:string;body:unknown}|null>(null);
 const [selected,setSelected]=useState(String(initialContentId??'')),[note,setNote]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('pending'),[page,setPage]=useState(1);
 const staff=!!staffCandidateId;
 useEffect(()=>{let active=true;setLoading(true);setError('');const query=new URLSearchParams({status:compact?'pending':status,search:compact?'':search,page:String(page),pageSize:compact?'1':'5'});apiGet<Payload>((staff?`/api/staff/candidates/${staffCandidateId}/assignments`:'/api/assignments')+'?'+query).then(d=>{if(active){setData(d);setLoading(false);}}).catch(e=>{if(active){setError(e.message);setLoading(false);}});return()=>{active=false;};},[staffCandidateId,refresh,status,search,page,compact]);
 const change=async(path:string,body:unknown)=>{setBusy(true);setActionError('');setMessage('');try{await apiPost(path,body);setFailedAction(null);setMessage('Assignment updated.');setRefresh(v=>v+1);if(!path.endsWith('/cancel'))setNote('');}catch(e){setFailedAction({path,body});setActionError((e as Error).message);}finally{setBusy(false);}};
 const filtered=loading||error?[]:data?.assignments??[];
 const pages=Math.max(1,Math.ceil((data?.total??0)/(data?.pageSize??5))),current=Math.min(page,pages);
 useEffect(()=>{if(data&&!loading&&page>pages)setPage(pages);},[data,loading,page,pages]);
 return <section aria-label="Assigned practice" className="rounded-2xl border border-[var(--stint-border)] bg-[var(--stint-bg-card)] p-5 space-y-4">
  <div><h2 className="text-lg font-semibold">{staff?'Assign reading practice':'Practice from your coach'}</h2><p className="mt-1 text-xs text-[var(--stint-text-muted)]">A saved reading of the assigned passage marks it complete. Completion means practice recorded, not mastery. Newest pending assignments appear first.</p></div>
  {error&&<p role="alert" className="text-sm">{error} <button className="font-semibold text-[var(--stint-primary)]" onClick={()=>setRefresh(v=>v+1)}>Try again</button></p>}{actionError&&<p role="alert" className="text-sm">{actionError} <button disabled={busy} className="font-semibold text-[var(--stint-primary)]" onClick={()=>failedAction&&void change(failedAction.path,failedAction.body)}>Retry failed action</button></p>}{message&&<p role="status" className="text-sm">{message}</p>}
  {loading&&!data?<p role="status" className="text-sm">Loading assignments…</p>:data&&<>
   {staff&&<form className="space-y-3 border-b border-[var(--stint-border)] pb-4" onSubmit={e=>{e.preventDefault();void change(`/api/staff/candidates/${staffCandidateId}/assignments`,{contentId:Number(selected),note});}}><p className="text-xs">Candidate domain: {data.candidate?.domain_name || 'Not assigned yet'}</p><label className="block text-sm">Passage<select required className={`${field} mt-1`} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a passage</option>{data.passages?.map(p=><option key={p.id} value={p.id}>{p.question}</option>)}</select></label>{!data.passages?.length&&<p className="text-sm">Assign the candidate a domain and classify an active passage before assigning practice.</p>}<label className="block text-sm">Coaching note<textarea className={`${field} mt-1`} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="For example: pause between sentences and finish each word."/></label><button disabled={busy||!selected||!data.passages?.some(p=>p.id===Number(selected))} className="rounded-xl bg-[var(--stint-primary)] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Assign passage</button></form>}
   {!compact && <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Search assignments<input className={`${field} mt-1`} type="search" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><label className="text-sm">Assignment status<select className={`${field} mt-1`} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="pending">Pending</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="">All statuses</option></select></label></div>}
   <p className="text-xs" aria-live="polite">{loading ? "Loading assignments…" : error ? "Results unavailable" : `${data.total ?? filtered.length} ${compact ? "pending assignments" : "matching assignments"}`}</p>
   {!loading&&!error&&!filtered.length&&<p className="py-3 text-sm text-[var(--stint-text-muted)]">{search?'No assignments match your search.':`No ${status || 'saved'} assignments. Your regular practice remains available.`}</p>}
   {filtered.map(a=>{const passage=passages.find(p=>p.id===a.content_id);return <article key={a.id} className="space-y-2 border-t border-[var(--stint-border)] pt-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="break-words text-sm font-semibold">{a.question}</h3><span className="text-xs font-medium">{a.status==='pending'&&!a.available?'Pending · unavailable':a.status}</span></div><p className="text-xs text-[var(--stint-text-muted)]">Assigned by {a.assigned_by_name} · {new Date(a.created_at).toLocaleDateString('en-IN')}</p>{a.note&&<p className="whitespace-pre-wrap break-words text-sm">{a.note}</p>}<div className="flex flex-wrap items-center gap-3">{!staff&&a.status==='pending'&&a.available&&passage&&<Link className="rounded-xl bg-[var(--stint-primary)] px-3 py-2 text-sm font-semibold text-white" to="/interview/session" state={{...passageState(passage),revisionFocus:{words:[],improvements:a.note?[a.note]:[]}}}>Start assigned practice</Link>}{a.completed_attempt_id&&<Link className="text-sm text-[var(--stint-primary)]" to={staff?`/staff/reports/${a.completed_attempt_id}`:`/reading/reports/${a.completed_attempt_id}`}>View completed reading</Link>}{staff&&a.status==='pending'&&<button disabled={busy} className="text-sm text-[var(--stint-primary)]" onClick={()=>void change(`/api/staff/assignments/${a.id}/cancel`,{})}>Cancel assignment</button>}</div>{a.status==='pending'&&(!a.available||(!staff&&!passage))&&<p className="text-xs text-[var(--stint-text-muted)]">This passage is no longer available in the candidate’s current domain. A coach can cancel this assignment and choose a new passage.</p>}</article>;})}
   {!compact&&pages>1&&<nav className="flex items-center justify-between text-sm" aria-label="Assignment pages"><button disabled={current===1} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current} of {pages}</span><button disabled={current===pages} onClick={()=>setPage(current+1)}>Next</button></nav>}
   {compact&&<Link className="inline-block text-sm font-semibold text-[var(--stint-primary)]" to="/reading/assignments">View all assignments →</Link>}
  </>}
 </section>;
}
