import React, { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import type { InterviewEntry } from '../constants';
import type { Attempt } from './ReadingReport';
import { buildRevisionQueue } from '../lib/readingRevision';
import { passageState } from './ReadingPracticePlan';
const field = 'mt-2 block w-full min-w-0 rounded-xl border border-[var(--stint-border)] bg-[var(--stint-bg-card)] px-3 py-2.5 text-sm';
export default function ReadingRevisionQueue({attempts,passages}:{attempts:Attempt[];passages:InterviewEntry[]}) {
  const [params,setParams]=useSearchParams();
  const search=params.get('q')??'', topic=params.get('topic')??'', type=params.get('type')??'';
  const [page,setPage]=useState(1);
  const items=buildRevisionQueue(attempts,passages);
  const matches=items.filter(item=>(!topic || item.passage.category===topic) && (!type || (type==='revisit' ? ['words','feedback'].includes(item.kind) : item.kind===type)) && `${item.passage.question} ${item.words.join(' ')} ${item.passage.category}`.toLowerCase().includes(search.trim().toLowerCase()));
  const pages=Math.max(1,Math.ceil(matches.length/8)), activePage=Math.min(page,pages);
  const filter=(key:string,value:string)=>{const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);setParams(next,{replace:true});setPage(1);};
  return <section aria-label="Personal revision queue" className="space-y-5">
    <header><h1 className="text-2xl font-semibold">Your revision queue</h1><p className="mt-2 text-sm text-[var(--stint-text-muted)]">One next exercise, based on your saved feedback and currently available passages.</p><p className="mt-2 text-xs text-[var(--stint-text-muted)]">Based on your latest 50 saved readings. Flagged words come first, followed by other feedback, new passages and refreshers. Within each group, older readings come first. These are practice suggestions, not a ranking of ability.</p></header>
    <div className="grid gap-3 md:grid-cols-3"><label className="text-sm">Find a passage or word<input type="search" className={field} value={search} onChange={e=>filter('q',e.target.value)}/></label><label className="text-sm">Topic<select className={field} value={topic} onChange={e=>filter('topic',e.target.value)}><option value="">All topics</option>{[...new Set(items.map(i=>i.passage.category).filter(Boolean))].sort().map(t=><option key={t}>{t}</option>)}</select></label><label className="text-sm">Practice focus<select className={field} value={type} onChange={e=>filter('type',e.target.value)}><option value="">All exercises</option><option value="revisit">Feedback to revisit</option><option value="new">New in recent history</option><option value="refresh">Refreshers</option></select></label></div>
    <div className="flex flex-wrap items-center justify-between gap-2 text-sm"><p role="status">{matches.length ? `${(activePage-1)*8+1}–${Math.min(activePage*8,matches.length)} of ${matches.length} exercises` : '0 exercises'}</p>{(search||topic||type)&&<button onClick={()=>{setParams({},{replace:true});setPage(1);}} className="text-[var(--stint-primary)]">Clear filters</button>}</div>
    {!matches.length&&<p className="rounded-xl border border-[var(--stint-border)] p-5 text-sm">{items.length?'No matching exercises. Clear your filters to see your queue.':'No reading passages are available for your current access yet.'}</p>}
    {matches.slice((activePage-1)*8,activePage*8).map(item=><article key={item.passage.id} className="min-w-0 rounded-2xl border border-[var(--stint-border)] bg-[var(--stint-bg-card)] p-5 space-y-3"><p className="text-xs font-semibold text-[var(--stint-primary)]">{item.passage.category || 'Reading practice'} · {item.kind==='new'?'Try a passage':item.kind==='refresh'?'Refresh your reading':'Revisit feedback'}</p><h2 className="break-words text-base font-semibold">{item.passage.question}</h2><p className="text-sm text-[var(--stint-text-muted)]">{item.reason}</p>{item.words.length>0&&<div className="flex flex-wrap gap-2" aria-label="Words to rehearse">{item.words.slice(0,3).map(word=><span key={word} className="max-w-full break-all rounded-lg bg-amber-500/10 px-2 py-1 text-sm">{word}</span>)}{item.words.length>3&&<span className="text-xs">+{item.words.length-3} in the report</span>}</div>}{item.focus.length>0&&<p className="text-sm">{item.focus[0]}</p>}<p className="text-xs text-[var(--stint-text-muted)]">{item.attempt ? `Last saved: ${new Date(item.attempt.created_at).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata'})}. Rehearse one word in its sentence, then read the full passage.` : 'Read once, review your feedback, then repeat with one change.'}</p><div className="flex flex-wrap items-center gap-4"><Link className="rounded-xl bg-[var(--stint-primary)] px-4 py-2.5 text-sm font-semibold text-white" to="/interview/session" state={{...passageState(item.passage), revisionFocus: { words: item.words.slice(0,3), improvements: item.focus }}}>Practise this passage</Link>{item.attempt&&<Link className="text-sm text-[var(--stint-primary)]" to={`/reading/reports/${item.attempt.id}`}>View source report</Link>}</div></article>)}
    {pages>1&&<nav aria-label="Revision pages" className="flex items-center justify-between gap-3 text-sm"><button disabled={activePage===1} onClick={()=>setPage(activePage-1)}>Previous</button><span>Page {activePage} of {pages}</span><button disabled={activePage===pages} onClick={()=>setPage(activePage+1)}>Next</button></nav>}
  </section>;
}
